### ISSUE TITLE
error  NullPointerException, 程序还在继续正常跑, 不过log里有时出这种报错

### ISSUE THREAD

**Issue by DancingLeaf123** [JannsenYang/dingdong-helper#17]
更新订单确认信息成功
无可选的配送时间
java.lang.NullPointerException
        at Api.addNewOrder(Api.java:360)
        at Application.lambda$3(Application.java:78)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at Api.addNewOrder(Api.java:360)
        at Application.lambda$3(Application.java:78)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at Api.addNewOrder(Api.java:360)
        at Application.lambda$3(Application.java:78)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at Api.addNewOrder(Api.java:360)
        at Application.lambda$3(Application.java:78)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at Api.addNewOrder(Api.java:360)
        at Application.lambda$3(Application.java:78)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at Api.addNewOrder(Api.java:360)
        at Application.lambda$3(Application.java:78)
        at java.lang.Thread.run(Unknown Source)

**Comment by DancingLeaf123** [comment]
360 行的body
            String body = httpRequest.execute().body();
            System.out.println(body); 
`{       "success": false,       "code": -3001,  "msg": "当前人多拥挤，请稍后尝试刷新页面",      "tips": {               "duration": 300,          "limitMsg": "前方拥挤，请稍后再试..."   },      "barrier": {            "passRatio": 0.5,        "maxCount": 5    },      "data": {} }`

**Comment by JannsenYang** [comment]
能贴一下你的Api.java第360行是什么代码  不同commit版本行数不一样

**Comment by JannsenYang** [comment]
这个应该不会空指针异常的    这个是叮咚的限流策略  多发几次就成功了 就和你手点一样

**Comment by DancingLeaf123** [comment]
{"error":"AssertError","code":"405","data":"-405"}
java.lang.NullPointerException
        at Api.addNewOrder(Api.java:362)
        at Application.lambda$3(Application.java:78)
        at java.lang.Thread.run(Unknown Source)

**Comment by DancingLeaf123** [comment]
就以下

`            httpRequest.form(request);
            String body = httpRequest.execute().body();
            System.out.println(body); 
            JSONObject object = JSONUtil.parseObj(body);
            boolean success = object.getBool("success");
            if (!success) {`

**Comment by JannsenYang** [comment]
哦  我知道了 我改一下 代码   asserterror是被网关拉黑了 请求频率过高   看我的readme  注意事项第一项 不要长时间跑

**Comment by DancingLeaf123** [comment]
emmm多久算长时间呢, 因为一直抢不到呀~~~ 我早上6点居然没抢到, 货存没了

**Comment by JannsenYang** [comment]
叮咚只开放6点和8点半这两个时间点 其他时间不会上货  你跑也没有用  这两个时间没抢到就不要跑了

**Comment by DancingLeaf123** [comment]
高并发模式和单次模式怎么切换, 要注释哪部分代码呢

**Comment by JannsenYang** [comment]
> 高并发模式和单次模式怎么切换, 要注释哪部分代码呢

单次是用来在低峰期测试是否可以下单的 无实际意义 因为低峰期手机点也能下

**Comment by DancingLeaf123** [comment]
我注释了后面for loop部分, 前面几行放出来, 每次点会报错, 是不是这算跑不通?
java.lang.NullPointerException
        at Api.getMultiReserveTime(Api.java:156)
        at Application.main(Application.java:26)
java.lang.NullPointerException
        at Api.getCheckOrder(Api.java:223)
        at Application.main(Application.java:27)
Exception in thread "main" java.lang.NullPointerException
        at Api.addNewOrder(Api.java:295)
        at Application.main(Application.java:28)

**Comment by JannsenYang** [comment]
还是相同的问题 被网关拦截了 我正在改代码 等会改好了会有准确提示

**Comment by DancingLeaf123** [comment]
我提供一点可能有帮助的信息, 我早上自己的地址和配送点是没有上面报错的, 我改了配送点和地址帮别人就有这个报错了.

**Comment by JannsenYang** [comment]
更新一下代码
