### ISSUE TITLE
根本就用不了，一直报错。

### ISSUE THREAD

**Issue by tianxin8848** [JannsenYang/dingdong-helper#172]
明明我api啥都都写好了，自己也算是有那么一点点的抓包常识了吧。
不知道为啥，倒霉。

-

**Comment by tianxin8848** [comment]
报错一直是这样。
C:\Users\10453\.jdks\corretto-1.8.0_312\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3\lib\idea_rt.jar=7392:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\charsets.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\ext\access-bridge-64.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\ext\cldrdata.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\ext\dnsns.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\ext\jaccess.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\ext\jfxrt.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\ext\localedata.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\ext\nashorn.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\ext\sunec.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\ext\sunjce_provider.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\ext\sunmscapi.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\ext\sunpkcs11.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\ext\zipfs.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\jce.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\jfr.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\jfxswt.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\jsse.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\management-agent.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\resources.jar;C:\Users\10453\.jdks\corretto-1.8.0_312\jre\lib\rt.jar;D:\dingdong-helper-main\dingdong-helper-main\target\classes;C:\Users\10453\.m2\repository\org\projectlombok\lombok\1.18.20\lombok-1.18.20.jar;C:\Users\10453\.m2\repository\com\google\guava\guava\31.1-jre\guava-31.1-jre.jar;C:\Users\10453\.m2\repository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\10453\.m2\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\10453\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\10453\.m2\repository\org\checkerframework\checker-qual\3.12.0\checker-qual-3.12.0.jar;C:\Users\10453\.m2\repository\com\google\errorprone\error_prone_annotations\2.11.0\error_prone_annotations-2.11.0.jar;C:\Users\10453\.m2\repository\com\google\j2objc\j2objc-annotations\1.3\j2objc-annotations-1.3.jar;C:\Users\10453\.m2\repository\cn\hutool\hutool-all\5.7.1\hutool-all-5.7.1.jar UserConfig
开始获取收货人信息
cn.hutool.core.io.IORuntimeException: File not exist: sign.js
	at cn.hutool.core.io.file.FileReader.checkFile(FileReader.java:300)
	at cn.hutool.core.io.file.FileReader.<init>(FileReader.java:57)
	at cn.hutool.core.io.file.FileReader.create(FileReader.java:37)
	at cn.hutool.core.io.FileUtil.readString(FileUtil.java:1872)
	at cn.hutool.core.io.FileUtil.readString(FileUtil.java:1860)
	at Api.sign(Api.java:52)
	at Api.checkUserConfig(Api.java:147)
	at UserConfig.main(UserConfig.java:25)
没有可用的默认收货地址，请自行登录叮咚设置该站点可用的默认收货地址

**Comment by Slowhy** [comment]
In the last line: "没有可用的默认收货地址，请自行登录叮咚设置该站点可用的默认收货地址"
Have you set a default shipping address?

**Comment by tianxin8848** [comment]
> 

我怎么就没设置地址啊，地址填抓包的字符吧？但是我抓包之后，就没有addressid这个选项，有了之后后面的也是空的。

**Comment by Miles0928** [comment]
> > 
> 
> 我怎么就没设置地址啊，地址填抓包的字符吧？但是我抓包之后，就没有addressid这个选项，有了之后后面的也是空的。

在叮咚APP或者小程序里把实际收货地址设置成默认值

**Comment by tianxin8848** [comment]
> > 我怎么就没设置地址啊，地址填抓包的字符吧？但是我抓包之后，就没有addressid这个选项，有了之后后面的也是空的。
> 
> 在叮咚APP或者小程序里把实际收货地址设置成默认值

默认值是把地址删掉再重新抓包？你们说的什么行业属于啊

**Comment by Meteor0928** [comment]
不需要抓包，也和程序没关系
登录你的叮咚客户端，找到你实际的收货地址 (对应设置的叮咚station ID)，把它编辑成默认收货地址

**Comment by Miles0928** [comment]
> > > 我怎么就没设置地址啊，地址填抓包的字符吧？但是我抓包之后，就没有addressid这个选项，有了之后后面的也是空的。
> > 
> > 
> > 在叮咚APP或者小程序里把实际收货地址设置成默认值
> 
> 默认值是把地址删掉再重新抓包？你们说的什么行业属于啊

不需要重新抓包，也和程序没关系
登录你的叮咚客户端，找到你实际的收货地址 (对应设置的叮咚station ID)，把它编辑成默认收货地址

**Comment by tianxin8848** [comment]
> > > > 我怎么就没设置地址啊，地址填抓包的字符吧？但是我抓包之后，就没有addressid这个选项，有了之后后面的也是空的。
> > > 
> > > 
> > > 在叮咚APP或者小程序里把实际收货地址设置成默认值
> > 
> > 
> > 默认值是把地址删掉再重新抓包？你们说的什么行业属于啊
> 
> 不需要抓包，也和程序没关系 登录你的叮咚客户端，找到你实际的收货地址 (对应设置的叮咚station ID)，把它编辑成默认收货地址

什么跟什么呀。我叮咚客户端是有默认地址的。就这还读不不出来，真不知道怎么解决这个错误。世纪难题。

**Comment by Miles0928** [comment]
> > > > > 我怎么就没设置地址啊，地址填抓包的字符吧？但是我抓包之后，就没有addressid这个选项，有了之后后面的也是空的。
> > > > 
> > > > 
> > > > 在叮咚APP或者小程序里把实际收货地址设置成默认值
> > > 
> > > 
> > > 默认值是把地址删掉再重新抓包？你们说的什么行业属于啊
> > 
> > 
> > 不需要抓包，也和程序没关系 登录你的叮咚客户端，找到你实际的收货地址 (对应设置的叮咚station ID)，把它编辑成默认收货地址
> 
> 什么跟什么呀。我叮咚客户端是有默认地址的。就这还读不不出来，真不知道怎么解决这个错误。世纪难题。

那你慢慢琢磨吧，祝你好运！

**Comment by tianxin8848** [comment]
> > > > > > 我怎么就没设置地址啊，地址填抓包的字符吧？但是我抓包之后，就没有addressid这个选项，有了之后后面的也是空的。
> > > > > 
> > > > > 
> > > > > 在叮咚APP或者小程序里把实际收货地址设置成默认值
> > > > 
> > > > 
> > > > 默认值是把地址删掉再重新抓包？你们说的什么行业属于啊
> > > 
> > > 
> > > 不需要抓包，也和程序没关系 登录你的叮咚客户端，找到你实际的收货地址 (对应设置的叮咚station ID)，把它编辑成默认收货地址
> > 
> > 
> > 什么跟什么呀。我叮咚客户端是有默认地址的。就这还读不不出来，真不知道怎么解决这个错误。世纪难题。
> 
> 那你慢慢琢磨吧，祝你好运！

纯属是想用这技术试试运气罢了。没有这运气，你也不用祝福我，顺带说一句，这程序写备注的方法让人真看不懂，我只是想偷偷学点儿项目经验，看来不行，我速速滚蛋。

**Comment by Slowhy** [comment]
> > 
> 
> 我怎么就没设置地址啊，地址填抓包的字符吧？但是我抓包之后，就没有addressid这个选项，有了之后后面的也是空的。

![Uploading IMG_20220420_134046.jpg…]()
我在手机上抓是抓得到的

**Comment by Slowhy** [comment]
> > 
> 
> 我怎么就没设置地址啊，地址填抓包的字符吧？但是我抓包之后，就没有addressid这个选项，有了之后后面的也是空的。

![IMG_20220420_134046](https://user-images.githubusercontent.com/28828389/164158959-1c2ef97d-68bc-4c3c-baf0-9ff96092cfe2.jpg)
我在手机上抓是抓得到的emmmmmmm

**Comment by 1448399491** [comment]
> > > > > > > 我怎么就没设置地址啊，地址填抓包的字符吧？但是我抓包之后，就没有addressid这个选项，有了之后后面的也是空的。
> > > > > > 
> > > > > > 
> > > > > > 在叮咚APP或者小程序里把实际收货地址设置成默认值
> > > > > 
> > > > > 
> > > > > 默认值是把地址删掉再重新抓包？你们说的什么行业属于啊
> > > > 
> > > > 
> > > > 不需要抓包，也和程序没关系 登录你的叮咚客户端，找到你实际的收货地址 (对应设置的叮咚station ID)，把它编辑成默认收货地址
> > > 
> > > 
> > > 什么跟什么呀。我叮咚客户端是有默认地址的。就这还读不不出来，真不知道怎么解决这个错误。世纪难题。
> > 
> > 
> > 那你慢慢琢磨吧，祝你好运！
> 
> 纯属是想用这技术试试运气罢了。没有这运气，你也不用祝福我，顺带说一句，这程序写备注的方法让人真看不懂，我只是想偷偷学点儿项目经验，看来不行，我速速滚蛋。

阴阳怪气的 速速滚蛋

**Comment by tianxin8848** [comment]
### [](url)[](url)
![LHD$AXMDHRVV54R@I@IVW$H](https://user-images.githubusercontent.com/74229669/164164674-c88b2a30-461e-4cf5-bf0b-1255076c9930.png)就这样也叫抓到？真无语。

**Comment by 5venw0ng** [comment]
> > > > > > 我怎么就没设置地址啊，地址填抓包的字符吧？但是我抓包之后，就没有addressid这个选项，有了之后后面的也是空的。
> > > > > 
> > > > > 
> > > > > 在叮咚APP或者小程序里把实际收货地址设置成默认值
> > > > 
> > > > 
> > > > 默认值是把地址删掉再重新抓包？你们说的什么行业属于啊
> > > 
> > > 
> > > 不需要抓包，也和程序没关系 登录你的叮咚客户端，找到你实际的收货地址 (对应设置的叮咚station ID)，把它编辑成默认收货地址
> > 
> > 
> > 什么跟什么呀。我叮咚客户端是有默认地址的。就这还读不不出来，真不知道怎么解决这个错误。世纪难题。
> 
> 那你慢慢琢磨吧，祝你好运！

你回复他纯属多余，你看他的回复，根本就没好好看文档，以为自己有点技术就跃跃欲试，文档不看也就算了，报错信息也不看，然后就来发issues，别人怎么好用呢？我连抢3天了，还分给邻居了，我怎么没问题呢？就像@1448399491 说的，这种阴阳怪气的人就不配。

OpenSource 不是 FREE（免费），是 FREE（自由），不要只知道伸手拿别人的，找到问题原因，再解决了顺便提个PR不比你在这嘲讽帮助你的人更有意义？

**Comment by zhuProgramer** [comment]
真的好菜
