### ISSUE TITLE
求助：关于报错cn.hutool.core.io.IORuntimeException: File not exist: sign.js

### ISSUE THREAD

**Issue by Will-Sze** [JannsenYang/dingdong-helper#186]
默认地址是设置好了的
之前用非签名版本的程序没有问题
抓包数据也是对的（之前的版本都验证过）
换成现在这版签名版的程序后就一直报错如下：
cn.hutool.core.io.IORuntimeException: File not exist: sign.js
	at cn.hutool.core.io.file.FileReader.checkFile(FileReader.java:300)
	at cn.hutool.core.io.file.FileReader.<init>(FileReader.java:57)
	at cn.hutool.core.io.file.FileReader.create(FileReader.java:37)
	at cn.hutool.core.io.FileUtil.readString(FileUtil.java:1872)
	at cn.hutool.core.io.FileUtil.readString(FileUtil.java:1860)
	at Api.sign(Api.java:52)
	at Api.allCheck(Api.java:207)
	at ApplicationTest.main(ApplicationTest.java:15)
技术有限，不懂是为什么，求大佬指点。。

**Comment by ares0x** [comment]
sign.js 文件不存在？

**Comment by Miles0928** [comment]
增加签名功能的程序，根目录增加了一个sign.js文件，你是不是缺少这个文件

**Comment by Will-Sze** [comment]
> sign.js 文件不存在？

从报错来看是的 但是这个文件明明就在根目录下。。。

**Comment by Will-Sze** [comment]
> 增加签名功能的程序，根目录增加了一个sign.js文件，你是不是缺少这个文件

从报错来看是的 但是这个文件明明就在根目录下。。。
