### ISSUE TITLE
执行的时候显示这个，是有什么问题么

### ISSUE THREAD

**Issue by chouking** [JannsenYang/dingdong-helper#21]
win7+微信PC版小程序+IDEA

更新购物车数据失败:当前人多拥挤，请稍后尝试刷新页面
java.lang.NullPointerException
	at Api.addNewOrder(Api.java:360)
	at Application.lambda$main$3(Application.java:78)
	at java.lang.Thread.run(Thread.java:748)
更新购物车数据失败:当前人多拥挤，请稍后尝试刷新页面
更新订单确认信息失败:
提交订单失败,当前下单总金额：49.10 返回：当前人多拥挤，请稍后尝试刷新页面

中间那段是提示有什么问题么？谢谢

**Comment by JannsenYang** [comment]
更新一下最新代码  这个异常是接口被风控了   不能长时间执行程序 只有在6点和8点半叮咚开放下单的时候抢一到两分钟 抢不到就不要继续了 持续大量的请求会被风控

**Comment by chouking** [comment]
> 更新一下代码这个异常是接口风控最新了 不能长时间执行单程序只有在 6 点和 8 点半左右的叮咬开放下的时候抢一咚到两分钟抢到就不要了持续的大量请求会被风控

下载了最新代码，执行了一下，确实可以了下单，不过不让付钱了，苦啊，明天再试一下。
